from collections import defaultdict
from yaml import load

files, = glob_wildcards("data/{sample}/outs/filtered_feature_bc_matrix.h5")


include: "rules/spatial.smk"

resolution=config.get("resolution",["0.8","2.5"])

route=config.get("route","standart")

if route == "standart":
    rule all:
        input:
            expand("results/{sample}/clusteringTree/clusteringTree-{sample}.pdf",sample=files),
            expand(["results/{sample}/resolution-" + x + "/{sample}.umap.spatial.pdf" for x in resolution],sample=files),
            expand(["results/{sample}/resolution-" + x + "/{sample}.number-of-cells-per-cluster.xlsx" for x in resolution],sample=files),
            expand(["results/{sample}/resolution-" + x + "/{sample}.all-markers-forAllClusters.xlsx" for x in resolution],sample=files),
            expand(["results/{sample}/resolution-" + x + "/{sample}.positive-markers-forAllClusters.xlsx" for x in resolution],sample=files),
            expand("results/{sample}/spatial-markers/{sample}.spatial_markers.xlsx",sample=files),
            expand("results/{sample}/technicals/{sample}.n_counts.pdf",sample=files),
            expand("results/{sample}/technicals/{sample}.normalization.pdf",sample=files),
            expand("results/{sample}/TissueImage/{sample}.png",sample=files),
            expand("results/{sample}/selected-markers/plots",sample=files)


  
elif route == "decon":
    scrnadatafiles, = glob_wildcards("scrna/{datafile}.rds")
    models, = glob_wildcards("models/{modelfile}.rds")
    rule deconvolution:
        input:
            expand("results/{sample}/deconvolution/spotlight/{sample}-{datafile}-spotlight.pdf",datafile=scrnadatafiles,sample=files),
            expand("results/{sample}/deconvolution/gbm/{sample}-{modelfile}-gbm.pdf",modelfile=models,sample=files),
            expand("results/{sample}/deconvolution/seurat/{sample}-{datafile}-seurat.pdf",datafile=scrnadatafiles,sample=files),
            expand("results/{sample}/deconvolution/rctd/{sample}-{datafile}-rctd.pdf",datafile=scrnadatafiles,sample=files),
            expand("results/{sample}/deconvolution/dwls/{sample}-{datafile}-dwls.pdf",datafile=scrnadatafiles,sample=files),
            expand("tangram/{datafile}/{sample}.csv",datafile=scrnadatafiles,sample=files)
            #expand("results/{sample}/deconvolution/spotlight/{datafile}/"),
            #expand("results/{sample}/deconvolution/inhouse_gbm/{datafile}/"),
            #expand("results/{sample}/deconvolution/seurat/{datafile}/")

elif route == "clusterplots":
    rule plotting:
        input:
            expand(["results/{sample}/resolution-" + x + "/markers" for x in resolution],sample=files)

